# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # TODO add unit test runs here
          
  upload:    
    runs-on: ubuntu-latest
    needs: test
    name: Upload to DCP Storage

    steps:
    - uses: actions/checkout@v3

    - name: Skyline DataMiner Deploy Action
      uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@e0ec0ded7b59b3577dc16b0df05d6d244508aea5
      with:
        # The API-key generated in the DCP Admin app as authentication for a certain DataMiner System. E.g. g597e77412e34297b827c2570a8fa2bc
        api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
        # The path to the .sln file of the solution. Atm only DataMiner Automation Script solutions are supported. E.g ./Example/Script.sln.
        solution-path: ./AutomationScript.sln
        # The chosen name of the package. E.g. MyPackageName.
        package-name: LondonPackage
        # The version number for the package (format A.B.C). E.g. 1.0.1.
        version: 1.0.1
          
  deploy_stag:
    runs-on: ubuntu-latest
    needs: upload
    name: Deploy to DMS [Staging]

    steps:
      - name: Run a one-line script
        run: echo Deploy to staging system
        
  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_stag
    environment: production
    name: Deploy to DMS [Production]
    
    steps:
      - name: Run a one-line script
        run: echo Deploy to production system
        
  publish:
    runs-on: ubuntu-latest
    needs: deploy_stag
    name: Publish to Private Catalog

    steps:
      - name: Run a one-line script
        run: echo Publish to private catalog
          
          
